language: python
python:
  - "3.6"
install: "pip install -r requirements.txt"
before_script:
  - cp .env.example .env
  - python manage.py migrate
script:
  - python manage.py test --settings=statesapi.test_settings
os: False